
kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"

---

kind: Service
apiVersion: v1
metadata:
  name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: le-prod
spec:
    ingressClassName: nginx
    tls:
    - hosts:
      - test.eks.demo.hr
      secretName: test.eks.demo.hr

    rules:
    - host: test.eks.demo.hr
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: banana-service
              port: 
                number: 5678