apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    name: in-cluster
  project: default
  source:
    path: apps/banana
    repoURL: https://github.com/mskender/argocd-examples/
    targetRevision: HEAD